// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_get_group_assignments
IntegerVector cpp_get_group_assignments(NumericVector predictor, NumericVector cuts);
RcppExport SEXP _OptSurvCutR_cpp_get_group_assignments(SEXP predictorSEXP, SEXP cutsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type predictor(predictorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cuts(cutsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_group_assignments(predictor, cuts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OptSurvCutR_cpp_get_group_assignments", (DL_FUNC) &_OptSurvCutR_cpp_get_group_assignments, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_OptSurvCutR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
