# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib OptSurvCutR, .registration = TRUE
#' @noRd
cpp_get_group_assignments <- function(predictor, cuts) {
    .Call(`_OptSurvCutR_cpp_get_group_assignments`, predictor, cuts)
}

